title: This is SED datacorp!
author: SED data scientist
email: ot@sed.com
description: > # this means to ignore newlines until "baseurl:"
  SED datacorp website

# social links
twitter_username: ot
github_username:  ot
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
